name: document-template-repository-usages

on:
  push:
    branches:
      - 'master'

jobs:
  run:
    name: Build and test
    runs-on: ubuntu-18.04
    steps:
    - name: Template Repository Usage Action
      uses: maael/template-repository-usage-action@v1.1.0
      with:
          token: ${{ secrets.GH_TOKEN }}
